### ISSUE TITLE
Is there an option to make the parent node selectable?

### ISSUE THREAD

**Issue by dashty94** [mikepricedev/mui-tree-select#1]

**Comment by mikepricedev** [comment]
Hi @dashty94,

Short answer is **yes**.

1. You can duplicating the selectable branch node in `getChildren`, tag the duplicate, implement `isBranch`, check for the tag and return false when found.
2. I am working on a `isBranchSelectable` method that will be added to the API in the next update.

After implementing number 1 in a real project last week.  It  had some gotchas that clearly would be better handled by the component logic.

If you cannot wait for the update and use option 1.   Quick tip, the duplicate nodes will return the same `key` property when rendering them into options.  I had to implement `renderOption` so that I could intercept and unique-ify the `key` prop.

Respectfully,
MP

**Comment by dashty94** [comment]
> Hi @dashty94,
> 
> 
> 
> Short answer is **yes**.
> 
> 
> 
> 1. You can duplicating the selectable branch node in `getChildren`, tag the duplicate, implement `isBranch`, check for the tag and return false when found.
> 
> 2. I am working on a `isBranchSelectable` method that will be added to the API in the next update.
> 
> 
> 
> After implementing number 1 in a real project last week.  It  had some gotchas that clearly would be better handled by the component logic.
> 
> 
> 
> If you cannot wait for the update and use option 1.   Quick tip, the duplicate nodes will return the same `key` property when rendering them into options.  I had to implement `renderOption` so that I could intercept and unique-ify the `key` prop.
> 
> 
> 
> Respectfully,
> 
> MP
> 
> 

Thank you for the reply. Please keep us updated for the next release as well.

**Comment by mikepricedev** [comment]
[`isBranchSelectable`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#isBranchSelectable) has been implemented as of [1.0.0-beta.7](https://www.npmjs.com/package/mui-tree-select/v/1.0.0-beta.7).  Returning `true` will result in your branch Node being rendered as a leaf node as well.

![image](https://user-images.githubusercontent.com/8903808/172979024-e0d8a64b-1f5d-4418-94b4-8dfc62c14c26.png)

Note: by default branch nodes sort to the top of the options list.
![image](https://user-images.githubusercontent.com/8903808/172979248-219e6c2c-d450-4410-9c08-f6c2d451ce5f.png)

**Comment by kraussjo** [comment]
Hi again :-),

The described solution works fine, but may not be intuitive for users.

Would it be possible to select the branch node directly? So instead of a double entry. Then the text would be the selection and the arrow a drilldown.

![image](https://user-images.githubusercontent.com/38663002/203620411-d0b73f26-db5e-4b01-9fc2-26f6f1d4b019.png)


Thanks alot

**Comment by mikepricedev** [comment]
Hi @kraussjo,

I've mulled over this type of implementation too.  IMO in a case where **all** branches are selectable I think there is a lot merit to having your type of approach.

Unfortunately, I don't think it is technically possible with the current API.  The difficulties go pretty deep into the underlying MUI libraries.  

I do have plans to give Tree Select its own styled component, only using MUI's `useAutocomplete` for the autocomplete and filtering logic.   Currently it uses MUI's full styled `<Autocomplete />` component under the hood.  This may open up a path to **allowing** for this type of approach.

In the meantime, I am looking at a custom sorting option, via props, that would allow grouping the branch and the selectable branch option together.

Respectfully,
MP

**Comment by kraussjo** [comment]
Hi @mikepricedev 

Thanks for the answer!

Is it possible then at the moment to make the leaves different from the branches? For example with an icon, or font color or padding ? So that the user can at least see a difference (except for the arrow).

Also respectfully
Jo

**Comment by mikepricedev** [comment]
Hi @kraussjo,

Yes. You can override options render however you'd like.  Using any combination of these utils:

- [`DefaultOption`](https://mikepricedev.github.io/mui-tree-select/modules.html#DefaultOption) 
- [`getDefaultOptionProps`](https://mikepricedev.github.io/mui-tree-select/modules.html#getDefaultOptionProps)
- [`TreeSelectProps.renderOption`](https://mikepricedev.github.io/mui-tree-select/modules.html#getDefaultOptionProps)

This is how I added the descendent match numbers in this [example](https://github.com/mikepricedev/mui-tree-select/issues/4#issuecomment-1233313242).

`<DefaultOption />` uses MUI's [`ListItemButton`](https://mui.com/material-ui/api/list-item-button/) under the hood, so you can do some quick and dirty customizations right there.

If you don't want to use `<DefaultOption />`, you do have to deal with a more complicated state than in Autocomplete.  Which was one of the primary motivating factors behind exposing `DefaultOption` and `getDefaultOptionProps` as public utilities.   Tree Select must deal with 3 different types of options an Up Branch, Down Branch, and Leaf.

However, if you need a full custom solution there are no restrictions.  The best place to start would be look at implementation of [`DefaultOption`](https://github.com/mikepricedev/mui-tree-select/blob/b1e38a8ec62e7250926af3e5372cc131ac0d9a37/src/TreeSelect.tsx#L84) and the different types of props it gets depending on the option type (Up, Down, Leaf).
- [`BaseDefaultOptionsProps`](https://github.com/mikepricedev/mui-tree-select/blob/b1e38a8ec62e7250926af3e5372cc131ac0d9a37/src/TreeSelect.tsx#L61)
- [`UpBranchDefaultOptionsProps`](https://github.com/mikepricedev/mui-tree-select/blob/b1e38a8ec62e7250926af3e5372cc131ac0d9a37/src/TreeSelect.tsx#L66)
- [`DownBranchDefaultOptionsProps`](https://github.com/mikepricedev/mui-tree-select/blob/b1e38a8ec62e7250926af3e5372cc131ac0d9a37/src/TreeSelect.tsx#L74)

Then I'd look at  [`getDefaultOptionProps`](https://github.com/mikepricedev/mui-tree-select/blob/b1e38a8ec62e7250926af3e5372cc131ac0d9a37/src/TreeSelect.tsx#L193) which creates the 3 different props above from the arguments of `renderOption`.  There is a type definition for that method [here](https://github.com/mikepricedev/mui-tree-select/blob/b1e38a8ec62e7250926af3e5372cc131ac0d9a37/src/TreeSelect.tsx#L180).

And lastly look at [`TreeSelectRenderOptionState`](https://github.com/mikepricedev/mui-tree-select/blob/b1e38a8ec62e7250926af3e5372cc131ac0d9a37/src/TreeSelect.tsx#L163) which you get in the 3rd argument to `renderOption`.

If you can do what you need with `DefaultOption` and `getDefaultOptionProps` it is a lot simpler :)

Respectfully,
MP
