### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by emrahc** [mikepricedev/mui-tree-select#11]
I use next.js. I get some errors.  It works fine but  app crashes after a while later.

I get this server error

`SyntaxError: Unexpected token 'export'`

This is the error in the console.

![image](https://user-images.githubusercontent.com/23315417/211102771-ca9a9f3d-d79b-4d84-9add-8bc2a672c745.png)

**Comment by mikepricedev** [comment]
Hi @emrahc,

Thanks for the info.  I have NOT tested this component with SSR.  However, what I do find interesting is the SyntaxError.  "export" is a keyword for native JavaScript modules and for the **dist** build I am targeting a fairly new ES standard with ES modules.

```json
   "target": "ES2019",
   "module": "ES6"
```

I found this [post](https://stackoverflow.com/a/65939797/2376252) concerning deps in Next.js that use ES Modules.

If this works, let me know!

Respectfully,
MP

**Comment by emrahc** [comment]
I changed next.config.js like below and it worked

```
const withTM = require("next-transpile-modules")(["mui-tree-select"]);

module.exports = withTM({...}}
```

**Comment by mikepricedev** [comment]
> I changed next.config.js like below and it worked
> 
> ```
> const withTM = require("next-transpile-modules")(["mui-tree-select"]);
> 
> module.exports = withTM({...}}
> ```

@emrahc Thank you for posting the solution!
