### ISSUE TITLE
Search in the whole data 

### ISSUE THREAD

**Issue by Namec999** [mikepricedev/mui-tree-select#12]
Hello,

is it possible when being at country level, to search in all the children too.

best

**Comment by mikepricedev** [comment]
Hi @Namec999 ,

Yes, see #4.

My apologies for not responding sooner.   I got confused by the github email notifications and thought you had found what you were looking for.

Respectfully,
M Price

**Comment by Namec999** [comment]
thank you, i got on this post already but it seems that there is a probleme when adding multiple to the tree select component.

best
