### ISSUE TITLE
React 18?

### ISSUE THREAD

**Issue by harry-peirse** [mikepricedev/mui-tree-select#14]
Hi - thanks for such a useful library!
I'm getting an issue installing this because of it's peer dependency on react@"^17.0.0". Is it possible to allow 18 as well?
Thanks

**Comment by mikepricedev** [comment]
Hi @harry-peirse 

Thank you for bring this to my attention. The newest version now supports React 18 and I've also updated the examples to use React 18.

My strategy for allowing React 18 was to [remove](https://github.com/mikepricedev/mui-tree-select/commit/0f12d4ab00b915852a4744daf5302ae418d6abdb#diff-a593fc14fdef41aaf092f774b92cb74bafeda3e9559f8ae4762374bf4af80c92) the react peer deps from the package and allow it to fall through to the react peer dep for whatever @mui version you are using.

I am making a note of this here in case this causes any problems, please reference this issue.  I will leave it open for a week or so to make it easy to find.

Respectfully,
Michael Price

**Comment by harry-peirse** [comment]
Perfect, thanks for this - all looks good on my side now. Much appreciated for the quick response!
