### ISSUE TITLE
If you are using the default branch, the dropdown list looks different than when you manually selected the option.

### ISSUE THREAD

**Issue by mextek** [mikepricedev/mui-tree-select#15]
Hey Mike! Thanks for this component, it's really awesome! I'm trying to use it in my project, but have a problem with appearance of dropdown list when default branch is used.

here's the fork  of your codesandbox: https://codesandbox.io/s/peaceful-ritchie-b6r317

how it looks like:
![image](https://user-images.githubusercontent.com/16350248/224466909-688e03b9-4a71-42c7-b826-17d8429a8d36.png)

how it must be:
![image](https://user-images.githubusercontent.com/16350248/224466952-3e020e51-fe7d-4260-a936-46a10837f739.png)

**Comment by mikepricedev** [comment]
Hi @mextek,

You want the `defaultBranch` to be the parent of the `defaultValue`.  Currently they are the same value.  You can see the change [here](https://codesandbox.io/s/youthful-brook-lsbux2?file=/index.js).

Note line 107.

![image](https://user-images.githubusercontent.com/8903808/224494604-5b2837cf-21c6-4101-8d78-4b19ab2f9a34.png)

Hope this helps.

Respectfully,
M Price

**Comment by mextek** [comment]
@mikepricedev thank you very much 👍
