### ISSUE TITLE
 Is there an option to show all sub-branches as selectable ?

### ISSUE THREAD

**Issue by emrahc** [mikepricedev/mui-tree-select#16]
Hello i applied the solution in that issue.

#https://github.com/mikepricedev/mui-tree-select/issues/4

A filter option to search whole tree. It works well. But it shows sub branches as "X Matches". Is it possible to have a filter option to show all deep nested sub values selectable ? I have tried but no success. Thanks

**Comment by mikepricedev** [comment]
There are 2 different ways of thinking about that implementation here #8.

The 2nd example uses [isBranchSelectable](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#isBranchSelectable).  You can interpret that in your code as selecting all the sub-branches.
