### ISSUE TITLE
Module not found: Can't resolve '@mui/material/styled'

### ISSUE THREAD

**Issue by JRS-Developer** [mikepricedev/mui-tree-select#17]
Hello!

I'm trying to make use of the TreeSelect component but I'm getting this error:
```
./node_modules/mui-tree-select/dist/TreeSelect.js:2:0
Module not found: Can't resolve '@mui/material/styled'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/mui-tree-select/dist/index.js
./src/components/sellerDashboard/CatalogNewProduct.tsx
./pages/dashboard/catalog/product/new.tsx
```

I'm using Next.js 13.2.4 and mui with version 5.12.0.

Right now I configured next.config.js to use transpilePackages to fix another [issue](https://github.com/mikepricedev/mui-tree-select/issues/11) but now I'm getting this one.

Seeing the console I can see this:
![image](https://user-images.githubusercontent.com/77207702/231318031-108dce65-39b1-441b-b596-bba8488151f6.png)

**Comment by JRS-Developer** [comment]
Ok, making some research I found that the issue is when trying to use SSR: 
https://stackoverflow.com/a/69248890
Making use of `dynamic` and removing `transpilePackages` fixed it, but it takes some time to show the component.

**Comment by mikepricedev** [comment]
Hi @JRS-Developer,

Thanks you for posting the solution.  Hopefully this will help others with SSR too.  Just to confirm, this did work for you?

Respectfully,
M Price

**Comment by JRS-Developer** [comment]
> Hi @JRS-Developer,
> 
> Thanks you for posting the solution.  Hopefully this will help others with SSR too.  Just to confirm, this did work for you?
> 
> Respectfully,
> M Price

Yeah, it's working as I mentioned using `dynamic` and avoiding the use of `transpilePackages`
