### ISSUE TITLE
Parents value in input text

### ISSUE THREAD

**Issue by molotow11** [mikepricedev/mui-tree-select#18]
Hi, Guys!

How I can get parents values rendered in input text after selection?
So, currently I have like `City`, but I want to have like `Country, State, City`

**Comment by molotow11** [comment]
Ok, I've found this way:
```
              renderInput={(params) => {
                let fixedValue = '';
                if(params.inputProps.value) {
                  const inputValue = params.inputProps.value;
                  const parent = categoriesData.find((category: any) => {
                    return category.childs.some((child: any) => child.value === inputValue)
                  });
                  fixedValue = `${t(parent.name)}, ${inputValue}`;
                }
                return (
                  <TextField
                    {...params}
                    InputProps={{
                      ...params.InputProps,
                      startAdornment: null
                    }}
                    inputProps={{
                      ...params.inputProps,
                      value: fixedValue,
                    }}
                    label={t('location.fields.labels.categories')}
                  />
                )
              }}
```

**Comment by mikepricedev** [comment]
A note on the model:

TreeSelect has no opinion on how you structure your tree data.  This is why a [`getParent`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#getParent) and a [`getChildren`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#getChildren) are required.

The examples just use a canonical tree node interface.   Something you might see in a cs class.  But you can do it anyway you want.  

The next consequence of this (as you have a astutely noted) is that you can share the value/values state with your `renderInput` method to render the input to your needs using the knowledge of your tree.
