### ISSUE TITLE
How to set default selected value.

### ISSUE THREAD

**Issue by KalanaPerera** [mikepricedev/mui-tree-select#2]
Hi Mike,

Thank you very much for creating this amazing package. I have one question, how do we default set value? I couldn't able to find any props related to this. would you be able to help me with this? Thanks in advance. :)

**Comment by mikepricedev** [comment]
Hi @KalanaPerera ,

Because the `defaultValue` prop is passed through by [MUI Autocomplete](https://mui.com/material-ui/api/autocomplete/#props), it is default hidden as an "External" prop by the docs page.  Here is the direct link "[defaultValue](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#defaultValue)".

You can toggle show "Externals" in the upper right had corner of the docs page:
![Image](https://user-images.githubusercontent.com/8903808/183303301-5dd093e7-2b6d-4633-9d0a-0b10002f2027.png)

Thanks for pointing this out.  I just realized the `value` prop is being hidden for the same reason.  I am going to leave this open and see how I can get those props to display by default.

Quick note when dealing with defaults in this package.  There is also a [`defaultBranch`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#defaultBranch) prop.  The branch and value are related but can very independently.  If you want your options to default somewhere other than your tree root, you must provided this too.

Hope this helps!

**Comment by KalanaPerera** [comment]
hi @mikepricedev,

Thank you very much for the detailed explanation, appreciated it. tested and works fine! Have a good day!

**Comment by maheskumaras** [comment]
Hi Using this https://codesandbox.io/s/github/mikepricedev/mui-tree-select
How to set default selected value.

**Comment by mikepricedev** [comment]
@maheskumaras 
My apologies I am not sure I understand the question.  Hopefully the following helps.

You can set a [`defaultValue`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#defaultValue) or you can control the [`value`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#value). 

And changes can captured with the [`onChange`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#onChange) callback.

**Comment by maheskumaras** [comment]
Hi thank you for the reply, My question is, In this sandbox (https://codesandbox.io/s/github/mikepricedev/mui-tree-select) you are showing city list right, how to set a city by default selected?.

This is the wonderful component my project manager wanted use this component only. so pls help me out.

ex:  value={{ id: "1-3901-52", name: "Ashkāsham" }}

<img width="576" alt="image" src="https://user-images.githubusercontent.com/60594691/186821302-33bd8f74-9c12-4659-bb02-ea95b913ad51.png">

**Comment by maheskumaras** [comment]
> hi @mikepricedev,
> 
> Thank you very much for the detailed explanation, appreciated it. tested and works fine! Have a good day!
Hi how you have solved this issue could you pls explain?

**Comment by maheskumaras** [comment]
Hi @KalanaPerera How you have solved above issue could pls explain?.

**Comment by KalanaPerera** [comment]
As I understand, you are trying to set, the default selected value, right? below code is from my current project. 

const defaultSelected = 'Electronics'  is string wraped in Node Class. 


```
<TreeSelect
        defaultValue={ defaultSelected !== null ? new Node(defaultSelected) : null}
        renderInput={(params) => (
          <TextField
            {...params}
            label="Category"
          />
        )}
        sx={{ ml: 2 }}
      />
```

**Comment by KalanaPerera** [comment]
> Hi thank you for the reply, My question is, In this sandbox (https://codesandbox.io/s/github/mikepricedev/mui-tree-select) you are showing city list right, how to set a city by default selected?.
> 
> This is the wonderful component my project manager wanted use this component only. so pls help me out.
> 
> ex: value={{ id: "1-3901-52", name: "Ashkāsham" }}
> 
> <img alt="image" width="200" src="https://user-images.githubusercontent.com/60594691/186821302-33bd8f74-9c12-4659-bb02-ea95b913ad51.png">

This is a different error, you need to check how the example work. please carefully look NODE Class.

Node Class: https://codesandbox.io/s/github/mikepricedev/mui-tree-select?file=/example/index.js

**Comment by KalanaPerera** [comment]
> Hi thank you for the reply, My question is, In this sandbox (https://codesandbox.io/s/github/mikepricedev/mui-tree-select) you are showing city list right, how to set a city by default selected?.
> 
> This is the wonderful component my project manager wanted use this component only. so pls help me out.
> 
> ex: value={{ id: "1-3901-52", name: "Ashkāsham" }}
> 
> <img alt="image" width="276" src="https://user-images.githubusercontent.com/60594691/186821302-33bd8f74-9c12-4659-bb02-ea95b913ad51.png">

This is a different error, you need to check how the example work. please carefully look NODE Class.

Node Class: https://codesandbox.io/s/github/mikepricedev/mui-tree-select?file=/example/index.js

**Comment by maheskumaras** [comment]
Hi @KalanaPerera, 
In this example https://codesandbox.io/s/github/mikepricedev/mui-tree-select?file=/example/index.js how you can we set value with a **controlled** state?

**Comment by KalanaPerera** [comment]
what do you mean programmatically? like API call?

**Comment by mikepricedev** [comment]
> 
You must implement `getChildren` and `getParent` callbacks and pass them as params to `TreeSelect`.  Documented [here](https://github.com/mikepricedev/mui-tree-select#basic-requirements).

What is happening with your error is that you are passing the city object to the `value` param, but the example code uses a wrapper class called `Node`.  

You must wrap that city value in the `Node` class. `value={new Node({id:"1-3901-52", name: "AshkÄ sham"})}`

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/8903808/186978719-ae742001-fd41-48b2-a775-2b2dcaf0b680.png">

Here is a [sandbox](https://codesandbox.io/s/withered-wave-nspw0x?file=/index.js:1972-1983) with a working `defaultValue` and controlled default `value` example.

Note: you **DO NOT** have to use my implementation of a `Node` class in your own code.  `TreeSelect` knows nothing about `Node` other than what I've told it through the `TreeSelect` callback params.

**Comment by mikepricedev** [comment]
@maheskumaras 
PS If you are using `TreeSelect` in a  production project, the current v1.0.0-beta.7 API is **stable**.

The only reason I have not published a v1.0.0 is that I am working on the docs.  And I want to add sandbox example dedicated to defaults.  Because the value and branch can vary independently it can be a little confusing how to set a default state.

Outside of bug fixes, nothing major if anything will change before v1.

**Comment by maheskumaras** [comment]
@mikepricedev Thank you very much its works fine.
and Thank you for the support @KalanaPerera

**Comment by kraussjo** [comment]
Hi all and thanks for that nice component!!

Setting the default value works nice. But:

Is it possible that the tree opens where the default value is set. Currently you still have to navigate to this value.


Thanks alot

**Comment by mikepricedev** [comment]
Hi @kraussjo,

There is a [`defaultBranch`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#defaultBranch) property for uncontrolled situations and a [`defaultBranch`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#branch) property and [`onBranchChange `](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#onBranchChange) method for controlled.

Hope this helps!

Respectfully,
MP

**Comment by kraussjo** [comment]
Thank you for the answer!

How exactly do I get the default branch in controlled situations.  The default value I can simply set per

`const [value, setValue] = useState(
        () =>
            new Node({
                id: "1-2",
                name: "V1 P2 Manfred Müller",
            })
    );`

, but with the branch I would need the complete json object with the child elements.

`const [branch, setBranch] = useState(
        () =>
            new Node({
                id: "1",
                name: "V1 Manfred Müller",.......
            })
    );`


Many thanks!

**Comment by mikepricedev** [comment]
Hi @kraussjo,

You can get the branch changes with [`onBranchChange`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#onBranchChange)

```jsx
const [branch, setBranch] = useState( () => new Node({ id: "1", name: "V1 Manfred Müller",....... }) );

return <TreeSelect 
onBranchChange={useCallback((_, branch) => setBranch(branch), [])}
...
/>
```

>  with the branch I would need the complete json object with the child elements.

It really depends on how your `getChildren` and `getParent` callback props are implemented.

In the examples, I believe I created a `Node` class.  You are not required to use that kind of conical OOP representation of tree data.  I personally don't.  I just used it in the examples for familiarity.  

You can implement `getChildren` and `getParent` to lookup the children and parent respectively based on what branch  they are called with.

For example
```jsx
const [branch, setBranch] = useState( () => ({ id: "1", name: "V1 Manfred Müller",....... }) );
return <TreeSelect 
getParent={useCallback((node) => {
  const { id } = node;
  // lookup parent of node with id and return OR null if node has no parent
}, [])}
getChildren ={useCallback((node) => {
  if(node) { 
    const { id } = node;
    // look up children of id and return OR null if has no children
  } else {
    // lookup and return root node (first options at the top of the tree)
  }
}, [])}
onBranchChange={useCallback((_, branch) => setBranch(branch), [])}
...
/>

```

**Comment by kraussjo** [comment]
Hi @mikepricedev

thanks for the tips, it works great!!
