### ISSUE TITLE
How to search the whole tree

### ISSUE THREAD

**Issue by nivalderramas** [mikepricedev/mui-tree-select#4]
Hi Mikey, thanks again for this tool and your kind answers.
Is there any way to make a search trough the whole tree? I mean (according to the example provided), if you are in the county level, also being able of search for a given city.
Thanks a lot

**Comment by mikepricedev** [comment]
Hi @nivalderramas,

You could do this by implementing a [`filterOptions`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#filterOptions) callback.

You can search your tree with the `inputValue` from the state argument (2nd arg) on `filterOptions` e.g. [`state.inputValue`](https://github.com/mui/material-ui/blob/660b9da2485257c80ba8be5e1079756ccb07f85d/packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.d.ts#L13).   Then search the descendants of your options nodes.

```
const filterOptions = (options, { inputValue }) => options.filter((option) => {
    const searchDescendants = (node) => {
      const children = node.getChildren();
      if (children?.length) {
        return children.some((cNode) => {
          return (
            cNode.value.name
              .toLowerCase()
              .indexOf(inputValue.toLowerCase()) === 0 ||
            searchDescendants(cNode)
          );
        });
      }
      return false;
    };

    return (
      option.value.name
        .toLowerCase()
        .indexOf(inputValue.toLowerCase()) > -1 ||
      searchDescendants(option)
    );
  });
```

 
PS  the example is a  **depth** first search.  Probably would want to make `searchDescendants` **Breadth** first.  Or if you are only targeting cities.  Check that the `cNode` is a city.  This code will check countries and states too.

The only gotcha here is that when a branch is changed, the `inputValue` is cleared.  You would have to play with a controlled `inputValue` to set the input back after it is cleared during a branch change event.

You can also show the number matching descendants, by implementing a custom [`renderOption`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#renderOption).

Note: with TreeSelect there are 3 option types
* up branch
* down branch
* leaf node

There  is a  [`DefaultOption`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#renderOption) component and a [`getDefaultOptionProps`](https://mikepricedev.github.io/mui-tree-select/modules.html#getDefaultOptionProps) free method for returning custom option components from `renderOption`.

It works like this:
```
const renderOption = (...args) => {
  const [, option, { inputValue, pathDirection }] = args;

  if (pathDirection === "down" && inputValue.trim()) {
    const getNumMatches = (node, numMatches = 0) =>
      (node.getChildren() || []).reduce((numMatches, cNode) => {
        if (
          cNode.value.name
            .toLowerCase()
            .indexOf(inputValue.trim().toLowerCase()) === 0
        ) {
          numMatches++;
        }
        return getNumMatches(cNode, numMatches);
      }, numMatches);

    const numMatchedDescendants = getNumMatches(option);

    if (numMatchedDescendants) {
      const { ListItemTextProps, ...props } = getDefaultOptionProps(
        ...args
      );

      return (
        <DefaultOption
          {...props}
          ListItemTextProps={{
            ...ListItemTextProps,
            //Add a secondary text
            secondary: `${numMatchedDescendants} Matches`
          }}
        />
      );
    }
  }

  return <DefaultOption {...getDefaultOptionProps(...args)} />;
}
```

Here is a working [example](https://codesandbox.io/s/rough-shape-5vuh37?file=/index.js) of the custom `renderOption`

**Comment by kraussjo** [comment]
And me again :-), 

the search works great, but i would like it if there was an example where the search value would not disappear when going down or up. Above it was mentioned that you can solve this via a controlled input, but i can't get it to work properly.

Many thanks!

**Comment by mikepricedev** [comment]
Hi @kraussjo,

Try [this](https://codesandbox.io/s/rough-shape-5vuh37?file=/index.js).

Respectfully,
MP

**Comment by kraussjo** [comment]
Hi @mikepricedev 

it works great in uncontrolled situations, but not in controlled ones. Here the value is still overwritten. Problem is the query 

`if (
            isBranchSelectionRef.current &&
            reason === "reset" &&
            value === ""
          ) {
            return;
          }
          setInput(value);`

there the value is not empty.


Is there any solution?

Thanks alot!

**Comment by mikepricedev** [comment]
Hi @kraussjo,

Short answer is no, to change this behavior you will always have to override it.

There are 2 things going on in Tree Select.  
1. Autocomplete views a branch selection as a value selection, so it calls for a reset of the input with the name of the branch that was selected.  
2.  If the branch changes  and the input is not cleared, the input will filter the new set of options which is not a desired behavior.  Typically you end up with "no options", until the input is manually cleared by the user e.g.

![image](https://user-images.githubusercontent.com/8903808/203849427-9ca5f0ff-9886-489f-8b86-256be3815e3d.png)

Selecting the branch "Algeria" **without** clearing the input would yield

![image](https://user-images.githubusercontent.com/8903808/203849284-1c103661-9b11-4098-b35f-da0d5e189bc6.png)

In order to address both, Tree Select intercepts the input reset call from Autocomplete on branch selection and instead clears the input.

But the api does not prohibit you from overriding this behavior.

A principle I try to follow that the MUI team is really good at, is separating **implemented** from **implementable**.  The goal is to not make the API too specific to any use case.  But to be very permissive to customization, allowing for as many use cases as possible.

The MUI's team commitment to this is how I was able to use Autocomplete to create Tree Select.  Making Tree Select too particular to the use cases I can think of would likely exclude the needs and creatively of others.

An example were I'd like to see more flexibility is in the options overrides.  It is a little rigid.  I think you had asked about combining selectable branches and branch navigation in to one option.  The rigidity unfortunately I think excludes that option.  Although I not 100%.  If someone figures it out, please do post.  It would make a great advanced example in the forth coming v1 release.

Respectfully,
MP

**Comment by Namec999** [comment]
i have came through this post lately and i had already integrated some check box for selecting all the content of a node.

i want to add this features of filtering, but i stuck in succedding in it.

here is my code :

`/* eslint-disable */
import { useState, useMemo, useEffect, Dispatch, SetStateAction } from 'react';
import TreeSelect, { FreeSoloNode, DefaultOption, getDefaultOptionProps } from 'mui-tree-select';
import { TextField, ListItem } from '@mui/material';
import Checkbox from '@mui/material/Checkbox';
import IconButton from '@mui/material/IconButton';
import { useQueryClient } from '@tanstack/react-query';

class Node {
  constructor(value) {
    this.value = value;
  }

  getParent() {
    const parent = (() => {
      if ('groups' in this.value) {
        return null;
      }
    })();
    return parent ? new Node(parent) : parent;
  }

  getChildren() {
    if ('groups' in this.value) {
      return this.value.groups.map((group) => new Node(group));
    }
    return null;
  }

  isBranch() {
    return 'fleets' in this.value || 'groups' in this.value;
  }

  isEqual(to) {
    return to.value.id === this.value.id;
  }

  toString() {
    return this.value.name;
  }
}

const AssetsSelector = (props) => {

  const initialData =  useMemo(() => props.initialAssets?.split(','));

  const queryClient = useQueryClient();
  const [branch, setBranch] = useState(null);
  const [value, setValue] = useState([]);
  const [assetsSelectorData, setAssetsSelectorData] = useState([]);
  const [mySettings] = useState(queryClient.getQueryData(['user_features']));
  const [assets] = useState(queryClient.getQueryData(['assets_list']));
  const rawGroupsResult = queryClient.getQueryData(['groups_list']);

  const valueIds = useMemo(() => new Set(value.map(({ value }) => value.id)), [value]);

 useEffect(() => {
    if (initialData?.length > 0) {
      const valueReturned = []
      initialData.map((item) => valueReturned.push(parseInt(item)))
      // props.setAssets(valueReturned)

    // HERE FORMATE WELL THE INITIAL VALUES
    
    const initIdList = [];

    valueReturned.map((itemId) => {
      
        const currentAsset = assets.filter((x) => parseInt(x.Id) === itemId);
        if (currentAsset[0]?.Id) {
          if (mySettings[0].as === 0) {
            const z = new Node({ id: currentAsset[0].Id, name: currentAsset[0].r });
            return initIdList.push(z);
          } else if (mySettings[0].as === 1) {
            const z = new Node({ id: currentAsset[0].Id, name: currentAsset[0].c });
            return initIdList.push(z);
          } else if (mySettings[0].as === 2) {
            const z = new Node({
              id: currentAsset[0].Id,
              name: `${currentAsset[0].r} (${currentAsset[0].c})`,
            });
            return initIdList.push(z);
          } else if (mySettings[0].as === 3) {
            const z = new Node({
              id: currentAsset[0]?.Id,
              name: `${currentAsset[0].c} (${currentAsset[0].r})`
            });
            return initIdList.push(z);
          }
        }
    });

    setValue(initIdList);
    }
  }, [assets])
 
  useEffect(() => {
    if (value.length >= 0) {
    const valueReturned = []
    value.map((item) => valueReturned.push(item.value.id))
    props.setAssets(valueReturned)
  }
  }, [value]);


  /// here create the JSON Formated OK
  useEffect(() => {
    const groupsJSON = [];
    rawGroupsResult.map((item) => {
      const groupsIdList = [];

      if (item.l) {
        const listIds = item.l.split(',');

        listIds.map((itemId) => {
          if (assets) {
            const currentAsset = assets.filter((x) => parseInt(x.Id) === parseInt(itemId));
            if (currentAsset[0]?.Id) {
              if (mySettings[0].as === 0) {
                return groupsIdList.push({ id: currentAsset[0].Id, name: currentAsset[0].r });
              } else if (mySettings[0].as === 1) {
                return groupsIdList.push({ id: currentAsset[0].Id, name: currentAsset[0].c });
              } else if (mySettings[0].as === 2) {
                return groupsIdList.push({
                  id: currentAsset[0].Id,
                  name: `${currentAsset[0].r} (${currentAsset[0].c})`,
                });
              } else if (mySettings[0].as === 3) {
                return groupsIdList.push({
                  id: currentAsset[0]?.Id,
                  name: `${currentAsset[0].c} (${currentAsset[0].r})`,
                });
              }
            }
          }
        });
        groupsJSON.push({ id: item.gk, name: item.n, groups: groupsIdList });
      }
    });
    setAssetsSelectorData(groupsJSON);
  }, [rawGroupsResult, assets]);

  useEffect(() => {
    const arrayIds = [];
    value.map((node) => {
      arrayIds.push(node.value.id);
    });
  }, [value]);

  return (
      <TreeSelect
        branch={branch}
        onBranchChange={(_, branch) => void setBranch(branch)}
        getChildren={(node) =>
          node
            ? node.getChildren()
            : assetsSelectorData.map((groups) => new Node(groups))
        }
        getParent={(node) => node.getParent()}
        isBranch={(node) => node.isBranch()}
        isOptionEqualToValue={(option, value) => {
          return option instanceof FreeSoloNode
            ? value instanceof FreeSoloNode &&
                value.toString() === option.toString() &&
                (option.parent === null || value.parent === null
                  ? option.parent === value.parent
                  : option.parent.isEqual(value.parent))
            : value instanceof FreeSoloNode
            ? false
            : option.isEqual(value);
        }}
        multiple
        limitTags={5}
        renderInput={(params) => <TextField {...params} label="Assets" className="h-100" />} // 
        renderOption={(...args) => {
          const [, node, { pathDirection }] = args;

          const { key, ...props } = getDefaultOptionProps(...args);

          const leafNodes = (node.getChildren() || []).filter(
            ({ value }) => !('fleets' in value || 'groups' in value)
          );

          const isChecked = leafNodes.every(({ value }) => valueIds.has(value.id));

          if (pathDirection === 'up' && leafNodes.length) {
            return (
              <ListItem
                disablePadding
                key={key}
                dense={props.dense ?? true}
                secondaryAction={
                  <IconButton
                    edge="end"
                    aria-label="delete"
                    onClick={() => {
                      if (isChecked) {
                        const leafNodeIds = new Set(leafNodes.map(({ value }) => value.id));
                        setValue((curValue) =>
                          curValue.filter(({ value }) => !leafNodeIds.has(value.id))
                        );
                      } else {
                        setValue((curValue) => [
                          ...new Map(
                            [...curValue, ...leafNodes].map((node) => [node.value.id, node])
                          ).values(),
                        ]);
                      }
                    }}
                  >
                    <Checkbox checked={isChecked} />
                  </IconButton>
                }
              >
                <DefaultOption component="div" {...props} />
              </ListItem>
            );
          }
          return <DefaultOption key={key} {...props} />;
        }}
        value={value}
        onChange={(_, value) => void setValue(value)}
      />
  );
};

export default AssetsSelector;
`

**Comment by Namec999** [comment]
Hello it's Great,

i'am trying to add this with have multiple as TRUE.

but this time the inputValue seems to reset each time, a no more filtering is available.

**Comment by molotow11** [comment]
Hello, Guys!
Any solution how to show child option when searching?
E.g. I have `Houses -> Villas` tree and when searching for `Villa` this shows me only parent option `Houses`
