### ISSUE TITLE
Module Warning

### ISSUE THREAD

**Issue by Maxim-BC** [mikepricedev/mui-tree-select#6]
Hello! 
 When I launch a project, I get a warning:

- **WARNING in ./node_modules/mui-tree-select/dist/TreeSelect.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js)**

- **WARNING in ./node_modules/mui-tree-select/dist/usePromise.js
  Module Warning (from ./node_modules/source-map-loader/dist/cjs.js)**

- **WARNING in ./node_modules/mui-tree-select/dist/index.js
  Module Warning (from ./node_modules/source-map-loader/dist/cjs.js)**

- **WARNING in ./node_modules/mui-tree-select/dist/useTreeSelect.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js)**

Has anyone received such a warning? What should I do about it?

**Comment by mikepricedev** [comment]
Hi @Maxim-BC ,

I have not seen it.  Do you see this when using `TreeSelect` as a dep?  If so, does it appear during the build phase?  Also is it causing any build or runtime failures?

I found a [thread](https://stackoverflow.com/questions/63195843/webpack-module-warning-failed-to-parse-source-map-from-data-url) describing a similar issue.  It appears that it is related to a source-map parsing error and web-pack.

Respectfully,
M Price

**Comment by Maxim-BC** [comment]
Hello M Price,

This happens at the build stage when I run the "npm start" command in my application, and after launching these warnings appear in the terminal. But the application works as it should, and mui-tree-select works, and I didn't notice any errors. 

I don't use Webpack. 

I deleted the node_modules folder and reinstalled mui-tree-select several times, but it didn't help. 
The warnings remained.

Respectfully,
Maxim

**Comment by joshf** [comment]
Hi, 

I am also seeing the same issue with Create React App

This happens because the src directory is not included in the npm package so the source map cant find the original file

So can be fixed with either:

1. Include the src directory in the build
2. Not build the sourcemaps

Josh

**Comment by joshf** [comment]
@mikepricedev any chance in getting this warning fixed?

**Comment by mikepricedev** [comment]
> Hi,
> 
> I am also seeing the same issue with Create React App
> 
> This happens because the src directory is not included in the npm package so the source map cant find the original file
> 
> So can be fixed with either:
> 
> 1. Include the src directory in the build
> 2. Not build the sourcemaps
> 
> Josh

Thanks for this!  I do not have a project to replicate the issue.  Let me know if this https://github.com/mikepricedev/mui-tree-select/commit/7b40addb2dafa5331afd20d958b1e46c78b61d46 removes the warning. (it is published to npm).

Respectfully,
M Price

**Comment by joshf** [comment]
hi @mikepricedev yes this fixed it, thank you!
