### ISSUE TITLE
Select "All" children

### ISSUE THREAD

**Issue by EmirSoza** [mikepricedev/mui-tree-select#8]
Hi, Thank you for this amazing package.
I could not see an option to put "Select all" to select all child nodes. Am I missing something or are you planning to add it to your road map?

Thank you in advance.

**Comment by mikepricedev** [comment]
Hi @EmirSoza,

Here is an [example](https://codesandbox.io/s/vibrant-bird-qztjum?file=/index.js:3245-5166) of implementing a "select all" feature with the component API.  The magic happens in the [`renderOption`](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#renderOption) prop.

Respectfully,
MP

PS Drill down to a state with cities (i.e. leaf nodes) and you'll see the feature.

**Comment by Namec999** [comment]
what a greate piece of code !

is it possible when selecting a group showing in the autocomplete oly the name of the group, and not all it's content.

something that looks like : react-dropdown-tree-select

best

**Comment by mikepricedev** [comment]
Hi @Namec999,

You could use the [isBranchSelectable](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#isBranchSelectable) prop and the [renderTags](https://mikepricedev.github.io/mui-tree-select/interfaces/TreeSelectProps.html#renderTags) prop to do something like this.  It would be up to you in your own code to interpret the meaning of a selected branch as selecting all children of the branch.

Here is a very rough [example](https://codesandbox.io/s/black-tdd-8iob1t?file=/index.js).   It is by no means complete, but I hope it helps.

Respectfully,
Michael Price

PS I set **Afghanistan** as the default value as all the selectable branches are filtering to the bottom of the options.
