### ISSUE TITLE
MUI: The value provided to Autocomplete is invalid.

### ISSUE THREAD

**Issue by joshf** [mikepricedev/mui-tree-select#9]
I am seeing lots of warning in the console for MUI: The value provided to Autocomplete is invalid.

```
react_devtools_backend.js:4026 MUI: The value provided to Autocomplete is invalid.
None of the options match with `{"node":{"value":{"id":"GAMES_AND_CONSOLES","name":"Games & Consoles"}},"type":0,"path":[]}`.
You can use the `isOptionEqualToValue` prop to customize the equality test.
```

This can also be reproduced in the demo by selecting a city then opening the select again and clicking the back arrow

**Comment by mikepricedev** [comment]
Hi @joshf,

Thanks for bring this up!.  Tree select uses MUI-Autocomplete under the covers.  MUI-Autocomplete preforms a [**dev** env check](https://github.com/mui/material-ui/blob/8f7b7514e64f126f0f2a0ced8dcee252b25c68e9/packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js#L245) to make sure that the `options` prop of Autocomplete contains the `value` prop.  It is meant to help warn developers of a potential mismatch of those Autocomplete props.

The warning is not applicable to Tree select, luckily I have an idea on how to turn it off that I am working on for the v1 release that does not involve forking MUI Autocomplete.

Respectfully,
MP

**Comment by joshf** [comment]
Ah that's a good to know !

**Comment by mikepricedev** [comment]
Hi @joshf,

I went ahead and pushed out a fix in a new build.  That warning is supper annoying and long, especially when it is not applicable 😆 

Respectfully,
MP
